/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import clases.conectar;
import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDate;
import javax.swing.JOptionPane;
/**
 *
 * @author pc
 */
public class formulario extends javax.swing.JFrame {

    conectar conecto;
    
    PreparedStatement ps;
    ResultSet rs;
    
    private static com.mysql.jdbc.Connection conn;
    private static final String driver = "com.mysql.jdbc.Driver";
    private static final String user = "root";
    private static final String pass = "";
    private static final String url = "jdbc:mysql://localhost:3306/dblicor";  
    /**
     * Creates new form formulario
     */
    public formulario() {
        initComponents();
    }
    
    //Este metodo retorna la conexion.
    public Connection getConnection(){
        Connection conn = null;
        try{
            Class.forName(driver);
            conn = (com.mysql.jdbc.Connection) DriverManager.getConnection(url, user, pass);
            if(conn != null){
                System.out.println("La conexion se establecio bien con la DB");
            }  
        }catch(ClassNotFoundException | SQLException e){ 
            System.out.println("Error al conectar con la DB " + e);
        }
        return conn;
    }
    
    
    //Metodo para desconectar.
    public void desconectar(){
        conn = null;
        if (conn == null) {
            System.out.println("Se desconecto de la DB");
        }
    }
    
    public void borrarCajas(){
        cajaNombre.setText(null);
        cajaEmail.setText(null);
        cajaContraseña.setText(null);        
        cajaLicor.setText(null);        
        cajaNumtragos.setText(null);         
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jLTitulo = new javax.swing.JLabel();
        jLNombre = new javax.swing.JLabel();
        jLlogo = new javax.swing.JLabel();
        jLEmail = new javax.swing.JLabel();
        jLContraseña = new javax.swing.JLabel();
        jLLicor = new javax.swing.JLabel();
        jLNumtragos = new javax.swing.JLabel();
        cajaNombre = new javax.swing.JTextField();
        cajaEmail = new javax.swing.JTextField();
        cajaContraseña = new javax.swing.JPasswordField();
        cajaLicor = new javax.swing.JTextField();
        cajaNumtragos = new javax.swing.JTextField();
        bConectar = new javax.swing.JButton();
        bdesconectar = new javax.swing.JButton();
        bEnviar = new javax.swing.JButton();
        jlfondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLTitulo.setFont(new java.awt.Font("Century Schoolbook", 0, 24)); // NOI18N
        jLTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLTitulo.setText("Registro Best Liqueur");
        getContentPane().add(jLTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 260, 60));

        jLNombre.setFont(new java.awt.Font("Century Schoolbook", 0, 18)); // NOI18N
        jLNombre.setForeground(new java.awt.Color(255, 255, 255));
        jLNombre.setText("Nombre:");
        getContentPane().add(jLNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 80, 40));

        jLlogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N
        getContentPane().add(jLlogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 140, -1, -1));

        jLEmail.setFont(new java.awt.Font("Century Schoolbook", 0, 18)); // NOI18N
        jLEmail.setForeground(new java.awt.Color(255, 255, 255));
        jLEmail.setText("Email:");
        getContentPane().add(jLEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 80, 30));

        jLContraseña.setFont(new java.awt.Font("Century Schoolbook", 0, 18)); // NOI18N
        jLContraseña.setForeground(new java.awt.Color(255, 255, 255));
        jLContraseña.setText("Contraseña:");
        getContentPane().add(jLContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, -1, -1));

        jLLicor.setFont(new java.awt.Font("Century Schoolbook", 0, 18)); // NOI18N
        jLLicor.setForeground(new java.awt.Color(255, 255, 255));
        jLLicor.setText("Licor Favorito:");
        getContentPane().add(jLLicor, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, -1, -1));

        jLNumtragos.setFont(new java.awt.Font("Century Schoolbook", 0, 18)); // NOI18N
        jLNumtragos.setForeground(new java.awt.Color(255, 255, 255));
        jLNumtragos.setText("# tragos al dia:");
        getContentPane().add(jLNumtragos, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 390, -1, -1));
        getContentPane().add(cajaNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 200, 30));
        getContentPane().add(cajaEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, 210, 30));

        cajaContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaContraseñaActionPerformed(evt);
            }
        });
        getContentPane().add(cajaContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, 200, 30));
        getContentPane().add(cajaLicor, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 350, 170, 30));
        getContentPane().add(cajaNumtragos, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 390, 170, 30));

        bConectar.setFont(new java.awt.Font("Century Schoolbook", 0, 11)); // NOI18N
        bConectar.setText("CONECTAR");
        bConectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bConectarActionPerformed(evt);
            }
        });
        getContentPane().add(bConectar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 460, -1, -1));

        bdesconectar.setFont(new java.awt.Font("Century Schoolbook", 0, 11)); // NOI18N
        bdesconectar.setText("DESCONECTAR");
        bdesconectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdesconectarActionPerformed(evt);
            }
        });
        getContentPane().add(bdesconectar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 460, -1, -1));

        bEnviar.setFont(new java.awt.Font("Century Schoolbook", 0, 11)); // NOI18N
        bEnviar.setText("ENVIAR");
        bEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEnviarActionPerformed(evt);
            }
        });
        getContentPane().add(bEnviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 460, -1, -1));

        jlfondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondo.jpg"))); // NOI18N
        jlfondo.setLabelFor(jlfondo);
        jlfondo.setAutoscrolls(true);
        jlfondo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jlfondo, org.jdesktop.beansbinding.ELProperty.create("${icon}"), jlfondo, org.jdesktop.beansbinding.BeanProperty.create("icon"));
        bindingGroup.addBinding(binding);

        getContentPane().add(jlfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 538));

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cajaContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaContraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaContraseñaActionPerformed

    private void bConectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bConectarActionPerformed
        // TODO add your handling code here:
        conecto = new conectar();
        Connection reg = conecto.getConnection();
    }//GEN-LAST:event_bConectarActionPerformed

    private void bdesconectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdesconectarActionPerformed
        // TODO add your handling code here:
        conecto.desconectar();
    }//GEN-LAST:event_bdesconectarActionPerformed

    private void bEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEnviarActionPerformed
        // TODO add your handling code here:
        Connection conn = null;
        try {
            conn = getConnection();
            ps = conn.prepareStatement("INSERT INTO datos(Nombre, Email, Contraseña, Licor , Num_tragos, Fechareg) VALUES(?,?,?,?,?,?)");
            ps.setString(1, cajaNombre.getText());
            ps.setString(2, cajaEmail.getText());
            ps.setString(3, cajaContraseña.getText());
            ps.setString(4, cajaLicor.getText());
            ps.setString(5, cajaNumtragos.getText());
            ps.setDate(6, Date.valueOf(LocalDate.now()));
            int result = ps.executeUpdate();
            if (result > 0) {
                JOptionPane.showMessageDialog(null, "Los datos fueron enviados correctamente");
                borrarCajas();
            } else {
                JOptionPane.showMessageDialog(null, "Los datos no fueron enviados");
            }
            conn.close();
            
        } catch (Exception e) {
            System.out.println(e);
        }
                                     
    }//GEN-LAST:event_bEnviarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formulario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bConectar;
    private javax.swing.JButton bEnviar;
    private javax.swing.JButton bdesconectar;
    private javax.swing.JPasswordField cajaContraseña;
    private javax.swing.JTextField cajaEmail;
    private javax.swing.JTextField cajaLicor;
    private javax.swing.JTextField cajaNombre;
    private javax.swing.JTextField cajaNumtragos;
    private javax.swing.JLabel jLContraseña;
    private javax.swing.JLabel jLEmail;
    private javax.swing.JLabel jLLicor;
    private javax.swing.JLabel jLNombre;
    private javax.swing.JLabel jLNumtragos;
    private javax.swing.JLabel jLTitulo;
    private javax.swing.JLabel jLlogo;
    private javax.swing.JLabel jlfondo;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
